### ISSUE TITLE
待完成事项

### ISSUE THREAD

**Issue by XiaogangSu** [guangmushikong/RoadDesignPrototype#5]
1、画线功能：在画线的同时可以拖动并放大缩小地图
2、纵断面联动查看：
     （1）地图界面规划线路附近点击，纵断面图自动跳转至点击位置的高程点处
     （2）跳转过程中纵断面图的缩放不变
3、图层组顺序控制
     （1）全球卫星影像或者地形晕眩图 （2）项目影像/眩晕 （3）通用矢量/map 行政区划（4）业务矢量层 （5）绘制overlay
      通用map的路线在最顶层显示   
4、纵断面在线生成功能
5、界面优化      
     （1）纵断面图起终点在平面路线上联动显示
     （2）按钮修改（加载本地按钮 ）
     （3）图层选择（图层匹配图标、不显示服务地址）

**Comment by xiaoyan-qq** [comment]
- [x] 画线功能：在画线的同时可以拖动并放大缩小地图
- [x] 纵断面联动查看
    - [x] 地图界面规划线路附近点击，纵断面图自动跳转至点击位置的高程点处
    - [x] 跳转过程中纵断面图的缩放不变
- -[x] 图层组顺序控制
    - [x] 全球卫星影像或者地形晕眩图 
    - [x] 项目影像/眩晕 
    - [x] 通用矢量/map 行政区划
    - [x] 业务矢量层 
    - [x] 绘制overlay
    - [x] 通用map的路线在最顶层显示
- -[x] 界面优化
    - [x] 纵断面图起终点在平面路线上联动显示
    - [x] 按钮修改（加载本地按钮 ）
    - [ ] 图层选择（图层匹配图标、不显示服务地址）
- -[x] 纵断面在线生成功能

**Comment by XiaogangSu** [comment]
![default](https://user-images.githubusercontent.com/13048706/40713504-b0fe780c-6432-11e8-8de5-75b021e7b82d.png)
